version: '3.1'
services:
  gateway-app:
    build: .
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    environment:
      - GATEWAY_APP_PORT=${APP_PORT:-5000}
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true