version: '3.1'
include:
  # - ./api-gateway/docker-compose.yml
  - ./inventory-service/docker-compose.yaml
services:
  gateway-app:
    extends: 
      file: ./api-gateway/docker-compose.yml
      service: gateway-app
    depends_on:
      - inventory-app
# networks:
#   ecommerce-network: