spring.application.name=inventory-service
server.port=${PORT:5001}
spring.data.mongodb.authentication-database=admin
spring.data.mogodb.username=${MONGODB_USERNAME:}
spring.data.mogodb.password=${MONGODB_PASSWORD:}
spring.data.mongodb.uri=${MONGODB_URI:}
spring.data.mongodb.auto-index-creation=true