version: '3.1'

services:

  inventory-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:?error}
      MONGO_INITDB_DATABASE: ecommerce
    networks:
      - module-network
      - ecommerce-network
    volumes:
      - /data/db

  db-gui:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - inventory-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME:?error}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:?error}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME:?error}:${DB_PASSWORD:?error}@inventory-db:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - module-network
      - ecommerce-network

  inventory-app:
    build: .
    ports:
      - "${APP_PORT:-5001}:${APP_PORT:-5001}"
    depends_on:
      - inventory-db
    environment:
      INVENTORY_PORT: ${APP_PORT:-5001}
      INVENTORY_MONGODB_USERNAME: ${DB_USERNAME:?error}
      INVENTORY_MONGODB_PASSWORD: ${DB_PASSWORD:?error}
      INVENTORY_MONGODB_URI: mongodb://${DB_USERNAME:?error}:${DB_PASSWORD:?error}@inventory-db:27017/ecommerce?authSource=admin
    networks:
      - module-network
      - ecommerce-network

networks:
  module-network:
  ecommerce-network:
    external: true